version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: portier
      POSTGRES_USER: portier
      POSTGRES_PASSWORD: portier
      POSTGRES_HOST_AUTH_METHOD: trust
