version: '3.7'

services:
  mongo:
    image: mongo:5.0-focal
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: portier
      MONGO_INITDB_ROOT_PASSWORD: portier
      MONGO_INITDB_DATABASE: portier
