---
spring:
  profiles:
    active: local
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:portier}
    username: ${DB_USERNAME:portier}
    password: ${DB_PASSWORD:portier}
    hikari:
      connection-timeout: 30000
  flyway:
    default-schema: portier
    schemas:
      - portier

logging:
  level:
    com.github.discordportier.server: DEBUG

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui
  api-docs:
    path: /swagger/api-docs

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT:}

management:
  server:
    port: ${MANAGEMENT_PORT:8081}
    base-path: ${MANAGEMENT_CONTEXT:}
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
