[versions]
log4j = "2.14.1"
kotlin-logging = "2.0.10"
jackson = "2.12.5"
ktor = "1.6.3"

[libraries]
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j18 = { module = "org.apache.logging.log4j:log4j-slf4j18-impl", version.ref = "log4j" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logging" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-jackson = { module = "io.ktor:ktor-jackson", version.ref = "ktor" }

[bundles]
log4j-impl = ["log4j-api", "log4j-core", "log4j-slf4j18"]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind", "jackson-yaml"]
ktor-server = ["ktor-server-core", "ktor-server-netty", "ktor-websockets", "ktor-jackson"]

[plugins]
